services:
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "yarn install && yarn dev"
    depends_on:
      - backend

  backend:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.9
    volumes:
      - ./backend:/app
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydb
    depends_on:
      - db
      - redis
      - qdrant

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"   # REST API
      - "6334:6334"   # gRPC API（使わないなら不要）
    volumes:
      - ./qdrant_storage:/qdrant/storage


  image-generator:
    build:
      context: ./sd-api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./sd-api:/app
    depends_on:
      - redis
      - qdrant

volumes:
  pgdata:
  qdrant_storage:
  redis-data:
